# Generated by Django 5.0.2 on 2024-04-24 10:21

import core.validators
import django.db.models.deletion
import django_ulid.models
import ulid.api.api
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=24, validators=[core.validators.NameValidator()], verbose_name='Title')),
                ('start_price', models.PositiveBigIntegerField(verbose_name='Start price')),
                ('picture', models.ImageField(default='lots_imgs/default.jpg', upload_to='lots_imgs', verbose_name='Picture')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_of_placement', models.DateTimeField(auto_now_add=True, verbose_name='date of placement')),
                ('date_of_end', models.DateField(verbose_name='date of end')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='categories.category', verbose_name='Lot category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_cities', to='core.city', verbose_name='City')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sellers', to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'db_table_comment': 'The model contains information about the lot. \n            See its status in "trading.TradeLog", see the bids for it in "bids.Bid"',
            },
        ),
    ]
