# Generated by Django 5.0.2 on 2024-04-12 17:48

import django.db.models.deletion
import lots.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivelots',
            name='buyer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(app_label)s_%(class)s_buyer', to=settings.AUTH_USER_MODEL, verbose_name='buyer'),
        ),
        migrations.AddField(
            model_name='archivelots',
            name='category',
            field=models.ForeignKey(default=1, on_delete=models.SET(lots.models.BaseLots._get_default_category), to='category.category', verbose_name='lot category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivelots',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_seller', to=settings.AUTH_USER_MODEL, verbose_name='seller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lots',
            name='buyer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(app_label)s_%(class)s_buyer', to=settings.AUTH_USER_MODEL, verbose_name='buyer'),
        ),
        migrations.AddField(
            model_name='lots',
            name='category',
            field=models.ForeignKey(default=1, on_delete=models.SET(lots.models.BaseLots._get_default_category), to='category.category', verbose_name='lot category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lots',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_seller', to=settings.AUTH_USER_MODEL, verbose_name='seller'),
            preserve_default=False,
        ),
    ]
