# Generated by Django 5.0.2 on 2024-03-01 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['user'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='users',
            name='banned',
        ),
        migrations.RemoveField(
            model_name='users',
            name='date_of_registration',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='surname',
        ),
        migrations.AddField(
            model_name='users',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='about',
            field=models.TextField(blank=True, default=None, verbose_name='About the user'),
        ),
        migrations.AddField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
