# Generated by Django 5.0.2 on 2024-03-31 18:44

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='buyer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='buyer'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='title',
            field=models.CharField(max_length=24, validators=[core.validators.NameValidator(only_letters=False)], verbose_name='lot name'),
        ),
    ]
