# Generated by Django 5.0.2 on 2024-03-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_alter_users_options_remove_users_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(default='/', max_length=48, verbose_name='path name'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='date_of_end',
            field=models.DateField(verbose_name='Date of end'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='Description of the lot'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='picture',
            field=models.ImageField(upload_to='lots_imgs'),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(upload_to='avatars'),
        ),
    ]
