# Generated by Django 5.0.2 on 2024-04-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_alter_lots_buyer_alter_lots_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lots',
            name='cost',
        ),
        migrations.AddField(
            model_name='lots',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='the price of the lot'),
            preserve_default=False,
        ),
    ]
