# Generated by Django 5.0.2 on 2024-04-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_remove_lots_cost_lots_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lots',
            options={'get_latest_by': '-date_of_placement', 'verbose_name': 'Lot', 'verbose_name_plural': 'Lots'},
        ),
    ]
