# Generated by Django 5.0.2 on 2024-04-25 17:34

import django_resized.forms
import django_ulid.models
import ulid.api.api
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_alter_lot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lot',
            name='picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='lots_imgs/default.jpg', force_format='JPEG', keep_meta=True, quality=86, scale=1, size=[286, 180], upload_to='lots_imgs', verbose_name='Picture'),
        ),
    ]
