# Generated by Django 5.0.2 on 2024-04-26 11:01

import django_ulid.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0005_alter_lot_id_alter_lot_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='date_of_placement',
        ),
        migrations.AlterField(
            model_name='lot',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lot',
            name='picture',
            field=models.ImageField(default='default/default_lot.jpg', upload_to='lots_imgs', verbose_name='Picture'),
        ),
    ]
