# Generated by Django 5.0.2 on 2024-04-26 12:08

import django_ulid.models
import ulid.api.api
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0006_remove_lot_date_of_placement_alter_lot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
    ]
