# Generated by Django 5.0.2 on 2024-04-30 19:31

import django_ulid.models
import ulid.api.api
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0014_alter_lot_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='date_of_end',
        ),
        migrations.AlterField(
            model_name='lot',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
    ]
