# Generated by Django 5.0.2 on 2024-04-24 10:21

import django.db.models.deletion
import django_ulid.models
import ulid.api.api
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('bid', models.PositiveIntegerField(help_text='The amount that the user has set', verbose_name='Bid')),
                ('trade', models.ForeignKey(help_text='The relationship with the TradeLogs table, which contains information about the lot and a link to the lot', on_delete=django.db.models.deletion.PROTECT, related_name='trading', to='trading.tradelog', verbose_name='Trade ID')),
                ('user', models.ForeignKey(help_text='The ID of the user who placed the bet', on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'db_table_comment': 'The model contains all the information about the bids of all users for all lots.\n            Attention! Adding/removing/moving bets without control entails the failure of the entire system.',
            },
        ),
    ]
