# Generated by Django 5.0.2 on 2024-04-24 16:17

import django_ulid.models
import ulid.api.api
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ('-id',), 'verbose_name': 'Bid', 'verbose_name_plural': 'Bids'},
        ),
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
    ]
