# Generated by Django 5.0.2 on 2024-03-31 13:20

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, unique=True, verbose_name='category name')),
                ('description', models.TextField(blank=True, default=None, verbose_name='description')),
                ('path', models.CharField(max_length=48, unique=True, validators=[core.validators.PathValidator()], verbose_name='path to category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
    ]
