# Generated by Django 5.0.2 on 2024-03-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="User's age"),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(blank=True, null=True, verbose_name="User's balance"),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name="The user's city"),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name="The user's phone number"),
        ),
        migrations.AlterField(
            model_name='user',
            name='purchases',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Purchases made by the user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sales',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sales made by the user'),
        ),
    ]
