# Generated by Django 5.0.2 on 2024-03-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_age_alter_user_avatar_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(default=1, verbose_name="User's age"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(verbose_name="User's balance"),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default=1, max_length=48, verbose_name="The user's city"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name="User's email"),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=48, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=48, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='purchases',
            field=models.PositiveSmallIntegerField(verbose_name='Purchases made by the user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sales',
            field=models.PositiveSmallIntegerField(verbose_name='Sales made by the user'),
        ),
    ]
