# Generated by Django 5.0.2 on 2024-03-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_age_alter_user_balance_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About the user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="The user's phone number"),
        ),
    ]
