# Generated by Django 5.0.2 on 2024-03-31 13:20

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_about_user_age_user_avatar_user_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name="user's age"),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=48, validators=[core.validators.CityValidator()], verbose_name="the user's city"),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=48, validators=[core.validators.NameValidator()], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=19, validators=[core.validators.PhoneNumberValidator()], verbose_name="the user's phone number"),
        ),
    ]
