# Generated by Django 5.0.2 on 2024-03-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_about_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(default=1, verbose_name="User's age"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, verbose_name="User's balance"),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=48, verbose_name="The user's city"),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name="The user's phone number"),
        ),
        migrations.AlterField(
            model_name='user',
            name='purchases',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Purchases made by the user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sales',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sales made by the user'),
        ),
    ]
