# Generated by Django 5.0.2 on 2024-03-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_age_alter_user_avatar_alter_user_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, verbose_name="User's balance"),
        ),
        migrations.AlterField(
            model_name='user',
            name='purchases',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Purchases made by the user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sales',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sales made by the user'),
        ),
    ]
