# Generated by Django 5.0.2 on 2024-04-24 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0002_alter_lot_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('06628dd4-d75a-7472-8000-0adaad5414c0'), primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Lot at auction'), (0, 'The bidding has been completed')], default=1)),
                ('current_price', models.PositiveIntegerField(help_text='The current price for the lot', verbose_name='Current price')),
                ('buyer', models.ForeignKey(help_text='The ID of the user who bought this lot', on_delete=django.db.models.deletion.PROTECT, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
                ('lot', models.OneToOneField(help_text='The ID of the lot', on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='lots.lot', verbose_name='Lot ID')),
            ],
            options={
                'verbose_name': 'Trade Log',
                'verbose_name_plural': 'Trade Logs',
                'db_table_comment': 'Log with records of the lots status.',
            },
        ),
    ]
