# Generated by Django 5.0.2 on 2024-04-24 11:16

import django.db.models.deletion
import django_ulid.models
import ulid.api.api
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelog',
            name='buyer',
            field=models.ForeignKey(help_text='The ID of the user who bought this lot', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
    ]
